#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) Netresearch DTT GmbH
#
# Generate docs/access-roster.md: who holds write, maintain or admin access
# to each active public repository of the organisation, and who owns the
# organisation.
#
# Usage:
#   scripts/generate-access-roster.sh [org] > docs/access-roster.md
#
# Requires: gh, authenticated with the read:org and repo scopes as an account
# with write access to every repository (the collaborators endpoint needs
# both), and jq.
# The roster is a snapshot. Re-run it after access changes; GOVERNANCE.md
# names the rule that keeps it current.

set -euo pipefail

ORG="${1:-netresearch}"

owners=$(gh api "orgs/${ORG}/members?role=admin&per_page=100" --paginate --jq '.[].login' | sort -f)
repos=$(gh api "orgs/${ORG}/repos?type=public&per_page=100" --paginate \
  --jq '.[] | select(.archived == false) | .name' | sort -f)

if [ -z "$owners" ] || [ -z "$repos" ]; then
  echo "::error::empty owner or repository list for ${ORG}; check the gh token scopes" >&2
  exit 1
fi

join() { paste -sd, - | sed 's/,/, /g'; }

cat <<EOF
# Access roster

Generated by \`scripts/generate-access-roster.sh\` on $(date -u +%Y-%m-%d).
The roster lists every account that can change code, settings or releases
of an active public repository of \`${ORG}\`. Roles are defined in
[GOVERNANCE.md](../GOVERNANCE.md#roles).

## Organisation owners

Owners hold admin access to every repository, the organisation settings,
the organisation secrets and the installed GitHub Apps:
$(printf '%s\n' "$owners" | awk '{ print "`" $0 "`" }' | join).

## Repositories

| Repository | Admin | Maintain | Write |
| --- | --- | --- | --- |
EOF

for repo in $repos; do
  collab=$(gh api "repos/${ORG}/${repo}/collaborators?affiliation=all&per_page=100" --paginate \
    --jq '.[] | [.login, .role_name] | @tsv')
  cell() {
    local list
    list=$(printf '%s\n' "$collab" | awk -F'\t' -v r="$1" '$2 == r { print "`" $1 "`" }' | sort -f | join)
    printf '%s' "${list:-none}"
  }
  printf '| [%s](https://github.com/%s/%s) | %s | %s | %s |\n' \
    "$repo" "$ORG" "$repo" "$(cell admin)" "$(cell maintain)" "$(cell write)"
done
