#!/usr/bin/env bash
# Sync a consuming repo with the canonical template.
#
# Usage:
#   scripts/sync-template.sh <template> <owner/repo> [--pr|--no-pr] [--branch <name>]
#
# Templates: go-app | go-lib
#
# Behavior:
#   1. Clones <owner/repo> via SSH into a temp worktree.
#   2. Creates a branch (default: sync/template-<template>-<timestamp>).
#   3. Copies templates/<template>/.github/ into the target, overwriting
#      matching files. template.yaml is ONLY created on first sync (never
#      overwritten — it carries per-repo intentional-drift state).
#   4. Commits (signed, DCO sign-off) if there are changes.
#   5. Pushes the branch and opens a PR via gh (default; --no-pr to skip).
#
# Requires: git, gh, bash 4+, ssh access to the target repo.

set -euo pipefail

TEMPLATE="${1:?template required: go-app or go-lib}"
TARGET="${2:?owner/repo required}"
shift 2 || true

MODE="pr"
BRANCH=""
while [ $# -gt 0 ]; do
  case "$1" in
    --pr) MODE="pr"; shift ;;
    --no-pr) MODE="no-pr"; shift ;;
    --branch) BRANCH="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

case "$TEMPLATE" in
  go-app|go-lib) ;;
  *) echo "unknown template: $TEMPLATE (want go-app|go-lib)" >&2; exit 2 ;;
esac

# Resolve script dir → project root (templates/ lives here).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_DIR="$PROJECT_ROOT/templates/$TEMPLATE/.github"

if [ ! -d "$TEMPLATE_DIR" ]; then
  echo "::error::template dir not found: $TEMPLATE_DIR" >&2
  exit 1
fi

[ -n "$BRANCH" ] || BRANCH="sync/template-${TEMPLATE}-$(date +%Y%m%d-%H%M%S)"

WORKTREE=$(mktemp -d -t sync-template-XXXXXX)
trap 'rm -rf "$WORKTREE"' EXIT

echo "[$TARGET] cloning…"
git clone --quiet "git@github.com:${TARGET}.git" "$WORKTREE/consumer"
cd "$WORKTREE/consumer"

DEFAULT_BRANCH=$(gh api "repos/${TARGET}" --jq '.default_branch')
git checkout "$DEFAULT_BRANCH" --quiet
git pull --quiet

# Drop the PR branch from any previous run, if any, to stay idempotent.
git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1 && \
  git push origin --delete "$BRANCH" >/dev/null 2>&1 || true

git checkout -b "$BRANCH" --quiet

# Copy template files. Overwrite matching paths, preserve repo-specific
# files that aren't in the template. template.yaml is special-cased:
# only created on first sync, never overwritten.
mkdir -p .github/workflows
cp -v "$TEMPLATE_DIR/dependabot.yml" .github/dependabot.yml
cp -v "$TEMPLATE_DIR/labeler.yml" .github/labeler.yml
if [ ! -f .github/template.yaml ]; then
  cp -v "$TEMPLATE_DIR/template.yaml" .github/template.yaml
else
  echo "note: preserving existing .github/template.yaml (carries intentional-drift state)"
fi

for wf in "$TEMPLATE_DIR/workflows"/*.yml; do
  cp -v "$wf" ".github/workflows/$(basename "$wf")"
done

if git diff --quiet && git diff --cached --quiet; then
  echo "[$TARGET] no changes vs template — already in sync."
  exit 0
fi

git add .github
git commit -S --signoff -m "ci: sync with netresearch/.github templates/$TEMPLATE

Auto-generated by scripts/sync-template.sh. Any changes you want to keep
must be declared in .github/template.yaml's intentional-drift: list — the
check-template-drift.yml job will otherwise revert them on next sync."

git push --set-upstream origin "$BRANCH"

if [ "$MODE" = "pr" ]; then
  gh pr create \
    --title "ci: sync with netresearch/.github templates/$TEMPLATE" \
    --body "Auto-opened by sync-template.sh. Brings this repo back into alignment with the canonical \`$TEMPLATE\` template in \`netresearch/.github\`.

To keep any diverging files, add their paths to \`.github/template.yaml\`'s \`intentional-drift:\` list before merging — otherwise the next sync run will revert them."
fi

echo "[$TARGET] sync complete on branch $BRANCH"
