name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  workflows:
    name: Lint Workflows
    uses: ./.github/workflows/lint-workflows.yml

  markdown:
    name: Lint Markdown
    uses: ./.github/workflows/lint-markdown.yml

  yaml:
    name: Lint YAML
    uses: ./.github/workflows/lint-yaml.yml
