name: Gitleaks Secret Scanning

on:
  workflow_call:
    inputs:
      skip:
        description: 'Skip secret scanning'
        required: false
        type: boolean
        default: false
    secrets:
      GITLEAKS_LICENSE:
        description: 'License key for Gitleaks'
        required: false

permissions: {}

jobs:
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >-
      !inputs.skip &&
      github.event_name != 'merge_group' &&
      github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
